function dydt = cr3bp(t,y)
    global mu
    r1 = norm([     mu+y(1),     y(2),   y(3) ]);
    r2 = norm([ -(1-mu-y(1)),    y(2),   y(3) ]);
    
    dydt = [    y(4)                                                       ;...
                y(5)                                                       ;...
                y(6)                                                       ;...
                y(1) - (1-mu)*(mu+y(1))/r1^3 + mu*(1-mu-y(1))/r2^3 + 2*y(5);...
                y(2) - (1-mu)*    y(2) /r1^3 - mu*      y(2) /r2^3 - 2*y(4);...
                     - (1-mu)*    y(3) /r1^3 - mu*      y(3) /r2^3         ];
end